---
# tasks file for monitoring prometheus

  - name: create directory for volumes config
    file:
      path: /home/{{ ansible_user }}/prometheus
      state: directory

  - name: copy prometheus.yml file
    template:
      src: templates/prometheus.yml.j2
      dest: /home/{{ ansible_user }}/prometheus/prometheus.yml
      mode: 0755

  - name: copy alert.rules file
    copy:
      src: templates/alert.rules
      dest: /home/{{ ansible_user }}/prometheus/alert.rules
      mode: 0755
    ignore_errors: true

  - name: create directory for volumes config
    file:
      path: /home/{{ ansible_user }}/grafana
      state: directory

  - name: create directory for volumes provisioning
    file:
      path: /home/{{ ansible_user }}/grafana/provisioning
      state: directory

  - name: create directory for volumes datasources
    file:
      path: /home/{{ ansible_user }}/grafana/provisioning/datasources
      state: directory

  - name: create directory for volumes dashboards
    file:
      path: /home/{{ ansible_user }}/grafana/provisioning/dashboards
      state: directory

  - name: copy datasource file
    template:
      src: templates/datasource.yml.j2
      dest: /home/{{ ansible_user }}/grafana/provisioning/datasources/datasource.yml
      mode: 0755

  - name: copy dashboard file
    template:
      src: templates/dashboard.yml.j2
      dest: /home/{{ ansible_user }}/grafana/provisioning/dashboards/dashboard.yml
      mode: 0755

  - name: copy dashboard node exporter full
    copy:
      src: templates/node-exporter-full.json
      dest: /home/{{ ansible_user }}/grafana/provisioning/dashboards/node-exporter-full.json
      mode: 0755

  - name: create directory for volumes config
    file:
      path: /home/{{ ansible_user }}/alertmanager
      state: directory

  - name: copy config.yml file
    template:
      src: templates/am.config.yml.j2
      dest: /home/{{ ansible_user }}/alertmanager/config.yml
      mode: 0755

  - name: copy docker-compose file
    copy:
      src: files/docker-compose.yml
      dest: /home/{{ ansible_user }}/docker-compose.yml
      mode: 0755

  - name: create and start services
    docker_compose:
      project_src: /home/{{ ansible_user }}
    register: output

  - name: show register
    debug: 
      var: output