---
# tasks file for monitoring docker install

  - name: Monitoring | Update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: Monitoring | Install docker
    apt:
      name: 
        - docker
        - docker-compose
      state: latest