---
# tasks file for monitoring node-exporter

  - name: create directory node-exporter
    file:
      path: /usr/local/bin/node-exporter
      state: directory
      mode: 0755

  - name: dowload node-exporter
    get_url:
      url: "{{ ne_get_url }}"
      dest: /tmp/node-exporter-{{ ne_ver }}.tar.gz

  - name: extract node-exporter
    unarchive:
      src: /tmp/node-exporter-{{ ne_ver }}.tar.gz
      dest: /tmp
      mode: 0755
      copy: no

  - name: mv node-exporter
    command: mv /tmp/node_exporter-{{ ne_ver }}.linux-amd64/node_exporter {{ ne_dir }}

  - name: create unit file
    template:
      src: templates/node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      mode: 644

  - name: enable service 
    systemd:
      name: node_exporter
      enabled: yes

  - name: start service
    systemd:
      state: started
      name: node_exporter
      daemon_reload: yes

  - name: service status
    command: systemctl status node_exporter.service
    register: status_ne

  - name: show status
    debug:
      var: status_ne.stdout_lines