---
# defaults file for monitoring

domain:          mydomainyouknow.fun
monitoring_host: monitoring

# variables for node-exporter

ne_dir:     /usr/local/bin
ne_ver:     1.4.0
ne_get_url: https://github.com/prometheus/node_exporter/releases/download/v{{ ne_ver }}/node_exporter-{{ ne_ver }}.linux-amd64.tar.gz
ne_port:    9100

# hosts for monitoring

www:             www.{{ domain }}
gitlab:          gitlab.{{ domain }}
runner:          runner.{{ domain }}
db01:            db01.{{ domain }}
db02:            db02.{{ domain }}
reverse:         app.{{ domain }}
grafana:         grafana.{{ domain }}
prometheus:      prometheus.{{ domain }}
alertmanager:    alertmanager.{{ domain }}
monitoring:      "{{ ansible_default_ipv4.address }}"

datasource_host: "{{ ansible_default_ipv4.address }}"

# service ports

grafana_port:       3000
prometheus_port:    9090
alertmanager_port:  9093