---
# defaults file for gitlab

runner: runner
gitlab: gitlab

gitlab_pass:  gitlab_pass
token_ce:     djlhl3Jw26U=

gitlab_host:  gitlab.mydomainyouknow.fun

gitlab_url:   http://gitlab.mydomainyouknow.fun
gitlab_urls:  https://gitlab.mydomainyouknow.fun

http_port:  "80"

www_ip:           "10.10.0.7"  
db01_ip:          "10.10.0.5"    
db02_ip:          "10.10.0.6"  
runner_ip:        "10.10.0.9"      
gitlab_ip:        "10.10.0.8"      
alertmanager_ip:  "10.10.0.10"     
prometheus_ip:    "10.10.0.10"   
grafana_ip:       "10.10.0.10"

# pacages for installation

gitlab_packages:
  - curl 
  - openssh-server 
  - ca-certificates 
  - tzdata 
  - perl

runner_packages:
  - curl
  - python3 
  - ansible
  - python3-pip