---
# tasks file for mysql apps

  - name: create db
    mysql_db:
      name: '{{ mysql_db }}'
      master_data: 1
      state: present
  
  - name: create user
    mysql_user:
      name: '{{ mysql_user }}'
      host: '%'
      password: '{{ mysql_pass }}'
      priv: '{{ mysql_db }}.*:ALL,GRANT'
      state: present