---
# tasks file for mysql install

  - name: update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: install Mysql
    apt:
      name: '{{ item }}'
      state: latest
    with_items:
      - mysql-server
      - python3-mysqldb