---
# tasks file for mysql

  - name: install packages
    include_tasks: install.yml

  - name:  setup mysql
    include_tasks: mysqld.yml
  
  - name: flush handlers
    meta: flush_handlers

  - name: configure replication
    include_tasks: replica.yml

  - name: create database and user
    include_tasks: apps.yml
    when: ansible_nodename == master_server 