---
# tasks file for mysql settings

  - name: Mysql configure | Enable remote login to mysql
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes
  
  - name: Mysql configure | server-id for db01
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      line: 'server-id = 1'
      create: yes
    when: ansible_nodename == "{{ primary_server }}"
    notify: restart mysql

  - name: Mysql configure | server-id for db02
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      line: 'server-id = 2'
      create: yes
    when: ansible_nodename == "{{ replica_server }}"
    notify: restart mysql