---
# tasks file for app nginx

  - name: Nginx | Update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true
  
  - name: Install nginx in Debian | Apt install
    apt:
      name: 
        - nginx
        - curl
      state: latest
    notify: Nginx start

  - name: Nginx config | Copy config files
    template:
      src: templates/{{ domain_zones }}.j2
      dest: /etc/nginx/sites-available/{{ domain_zones }}
      owner: www-data 
      group: www-data 
      mode: 0644

  - name: Nginx config | Copy config files
    template:
      src: templates/{{ domain_zones }}.ssl.j2
      dest: /etc/nginx/sites-available/{{ domain_zones }}.ssl
      owner: www-data 
      group: www-data 
      mode: 0644

  - name: Nginx config | Enable sites
    file:
      src: /etc/nginx/sites-available/{{ domain_zones }}
      dest: /etc/nginx/sites-enabled/{{ domain_zones }}
      state: link

  - name: Nginx config | Enable sites
    file:
      src: /etc/nginx/sites-available/{{ domain_zones }}.ssl
      dest: /etc/nginx/sites-enabled/{{ domain_zones }}.ssl
      state: link

  - name: Nginx config | Delete default config
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent