---
# tasks file for app php

  - name: PHP | Update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true
  
  - name: Install php | Apt install
    apt:
      name: 
      - php7.4
      - php7.4-fpm
      - php7.4-cli
      - php7.4-mysql
      - php7.4-curl
      - php7.4-json
      state: present
  