---
# tasks file for app php

  - name: update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true
  
  - name: install php
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ php_packages }}"
  