---
# tasks file for app wordpress

  - name: dowload wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress-latest.tar.gz

  - name: extract wordpress
    unarchive:
      src: /tmp/wordpress-latest.tar.gz
      dest: /tmp
      owner: www-data
      group: www-data
      mode: 0755
      copy: no
  
  - name: move wordpress
    command: mv /tmp/wordpress /var/www/{{ zones }}.{{ domain }}

  - name: fetch salts for wordpress
    command: curl https://api.wordpress.org/secret-key/1.1/salt/
    register: wp_salt


  - name: config wordpress
    template:
      src: templates/wp-config.j2
      dest: /var/www/{{ zones }}.{{ domain }}/wordpress/wp-config.php
      mode: 0755
    notify: 
      - apache reload