---
# handlers file for app

  - name: apache start
    systemd:
      state: started
      name: apache2
    
  - name: apache reload
    systemd:
      state: restarted
      daemon_reload: yes
      name: apache2

  - name: php5-fpm start
    service: 
      name: php5-fpm 
      state: started

  - name: php5-fpm restart 
    service: 
      name: php5-fpm 
      state: restarted