---
# tasks file for nginx insatall

  - name: update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: install nginx
    apt:
      name: nginx
      state: latest
    notify: nginx start

  - name: install certbot
    apt:
      name: certbot
      state: latest

  - name: install nginx plugins
    apt:
      name: python3-certbot-nginx
      state: latest

