---
# tasks file for nginx

  - name: install packages
    include_tasks: install.yml

  - name: setup proxy
    include_tasks: proxy.yml

  - name: flush handlers
    meta: flush_handlers
  
  - name: flush handlers
    meta: flush_handlers

  - name: create cert
    include_tasks: certbot.yml