---
# tasks file for nginx streams

  - name: Nginx config | Create directory available for domain_streams
    file:
      path: /etc/nginx/stream-available/
      state: directory

  - name: Nginx config | Create directory enabled for domain_streams
    file:
      path: /etc/nginx/stream-enabled/
      state: directory

  - name: Nginx config | Copy stream files
    template:
      src: templates/{{ item }}.stream.j2
      dest: /etc/nginx/stream-available/{{ item }}.stream
    with_items: "{{ domain_streams }}"

  - name: Nginx config | Enable streams
    file:
      src: /etc/nginx/stream-available/{{ item }}.stream
      dest: /etc/nginx/stream-enabled/{{ item }}
      state: link
    with_items: "{{ domain_streams }}"
    notify: Nginx reload