---
# deploy cluster tasks

  - name: Install Nginx
    hosts: you-node
    become: yes
    become_user: root
    remote_user: ubuntu
    roles:
      - nginx
    vars:
      nginx_user: www-data

  - name: Install MySQL
    hosts: db-node
    become: yes
    become_user: root
    remote_user: ubuntu
    roles:
      - mysql

  - name: Install Wordpress
    hosts: app-node
    become: yes
    become_user: root
    remote_user: ubuntu
    roles:
      - app
    vars:
      apache2_user: www-data

  - name: Install Gitlab
    hosts: gitlab-node
    become: yes
    become_user: root
    remote_user: ubuntu
    roles:
      - gitlab

  - name: Install Monitoring
    hosts: all
    become: yes
    become_user: root
    remote_user: ubuntu
    roles:
      - monitoring

  - name: Install Nginx
    hosts: you-node
    become: yes
    become_user: root
    remote_user: ubuntu
    roles:
      - cert
    vars:
      nginx_user: www-data