---
# tasks file for gitlab docker

  - name: copy docker-compose file
    copy:
      src: files/gitlab/docker-compose.yml
      dest: /home/{{ ansible_user }}/docker-compose.yml
      mode: 0755

  - name: create directory for volumes config
    file:
      path: /home/{{ ansible_user }}/gitlab-config
      state: directory

  - name: create directory for volumes data
    file:
      path: /home/{{ ansible_user }}/gitlab-data
      state: directory

  - name: create and start services
    docker_compose:
      project_src: /home/{{ ansible_user }}
    register: output

  - name: show register
    debug: 
      var: output
