---
# tasks file for gitlab docker runner

  - name: copy docker-compose file
    copy:
      src: files/runner/docker-compose.yml
      dest: /home/{{ ansible_user }}/docker-compose.yml
      mode: 0755

  - name: create directory runner-config for volumes
    file:
      path: /home/{{ ansible_user }}/runner-config
      state: directory

  - name: create directory ranner-docker.sock for volumes
    file:
      path: /home/{{ ansible_user }}/ranner-docker.sock
      state: directory

  - name: create and start services
    docker_compose:
      project_src: /home/{{ ansible_user }}
    register: output

  - name: show register
    debug: 
      var: output

  - name: copy config.toml ans register
    template:
      src: templates/config.j2
      dest: /home/{{ ansible_user }}/runner-config/config.toml
    notify: restart runner

  - name: flush handlers
    meta: flush_handlers

  - name: get register info
    command: docker exec -it {{ runner }} gitlab-runner list
    register: runner_status

  - name: show runner status
    debug:
      var: runner_status.stdout