---
# tasks file for gitlab install

  - name: update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: install packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ gitlab_packages }}"

  - name: install postfix
    apt:
      name:
        - postfix
      state: latest

  - name: download settings repository file
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
      dest: /home/{{ ansible_user }}
      mode: 0777

  - name: add gitlab repositiry
    command: ./script.deb.sh

  - name: install gitlab
    apt:
      name:
        - gitlab-ce
      state: latest

  - name: copy gitlab.rb
    template:
      src: templates/gitlab.rb.j2
      dest: /etc/gitlab/gitlab.rb

  - name: reconfigure
    command: gitlab-ctl reconfigure