---
# tasks file for gitlab install

  - name: Gitlab | Update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: Gitlab | Install packages
    apt:
      name: 
        - curl 
        - openssh-server 
        - ca-certificates 
        - tzdata 
        - perl
      state: latest

  - name: Gitlab | Install postfix
    apt:
      name:
        - postfix
      state: latest

  - name: Gitlab | Download settings repository file
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
      dest: /home/{{ ansible_user }}
      mode: '0777'

  - name: Gitlab | Add gitlab repositiry
    command: ./script.deb.sh

  - name: Gitlab | Install Gitlab
    apt:
      name:
        - gitlab-ce
      state: latest

  - name: Gitlab | Copy gitlab.rb
    template:
      src: templates/gitlab.rb.j2
      dest: /etc/gitlab/gitlab.rb

  - name: Gitlab | Reconfigure
    command: gitlab-ctl reconfigure