---
# tasks file for gitlab hosts

  - name: Hosts file | Add data about gitlab
    lineinfile:
      path: /etc/hosts
      line: "{{ gitlab_ip }} {{ gitlab }}.mydomainyouknow.fun"
      create: yes

  - name: Hosts file | Add data about runner
    lineinfile:
      path: /etc/hosts
      line: "{{ runner_ip }} {{ runner }}.mydomainyouknow.fun"
      create: yes