---
# tasks file for gitlab docker install

  - name: update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: install docker
    apt:
      name: 
        - docker
        - docker-compose
      state: latest