---
# tasks file for gitlab

  - name: install docker
    include_tasks: install-docker.yml
    when: ansible_nodename == runner 

  - name: configure and start
    include_tasks: gitlab.yml
    when: ansible_nodename == gitlab 

  - name: configure and start
    include_tasks: runner.yml
    when: ansible_nodename == runner 