---
# tasks file for gitlab runner

  - name: update apt cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600
    ignore_errors: true

  - name: install packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ runner_packages }}"

  - name: pip upgrade
    command: pip install --upgrade cryptography cffi \ pip install --upgrade pip wheel

  - name: upgrade ansible
    pip:
      name:
        - ansible
      state: latest
      extra_args: --user

  - name: install multi python packages
    pip:
      name:
        - ansible-lint==4.0.0

  - name: download settings repository file
    get_url:
      url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
      dest: /home/{{ ansible_user }}
      mode: 0777

  - name: add apt package gitlab-runner
    command: ./script.deb.sh

  - name: install gitlab-runner
    apt:
      name:
        - gitlab-runner
      state: latest

  - name: grant rights
    command: usermod -aG docker gitlab-runner

  - name: copy config.toml ans register
    template:
      src: templates/config.j2
      dest: /etc/gitlab-runner/config.toml
    notify: restart runner

  - name: flush handlers
    meta: flush_handlers

  - name: get register info
    command: gitlab-runner list
    register: runner_status

  - name: show runner status
    debug:
      var: runner_status.stdout